#!/usr/bin/env sh

echo "📝 Validating commit message..."

# Run commitlint with your config file
npx --yes commitlint --config commitlint.config.js --edit "$1"

if [ $? -eq 0 ]; then
  echo "✅ Commit message is valid!"
else
  echo "❌ Commit message validation failed!"
  exit 1
fi
